# -*- coding: utf-8 -*-
"""Calcfunction to collect the dynamical matrices of individual ``PhCalculation``s into a single ``FolderData``."""
from aiida.engine import calcfunction
from aiida.orm import FolderData
from aiida.plugins import CalculationFactory


@calcfunction
def recollect_qpoints(**kwargs):
    """Collect dynamical matrix files into a single folder.

    A different number is put at the end of each final dynamical matrix file, obtained from the input link, which
    corresponds to its place in the list of q-points originally generated by distribute_qpoints.

    :param kwargs: keys are the string representation of the q-point index and the value is the
        corresponding retrieved folder object. A special case is the folder at key '0' which is
        the folder of the initialization calculation.
    :return: FolderData object containing the dynamic matrix files of the computed PhBaseWorkChains
    """
    PhCalculation = CalculationFactory('quantumespresso.ph')
    dynmat_prefix = PhCalculation._OUTPUT_DYNAMICAL_MATRIX_PREFIX  # pylint: disable=protected-access

    # Initialize the merged folder, by creating the subdirectory for the dynamical matrix files
    merged_folder = FolderData()

    for key, retrieved_folder in kwargs.items():
        index = key.split('_')[-1]
        filepath_src = dynmat_prefix
        filepath_dst = f'{dynmat_prefix}{index}'
        
        if int(index) == 0:
            with retrieved_folder.base.repository.open(filepath_dst, 'rb') as handle:
                merged_folder.base.repository.put_object_from_filelike(handle, filepath_dst)
        else:
            with retrieved_folder.base.repository.open(filepath_src, 'rb') as handle:
                merged_folder.base.repository.put_object_from_filelike(handle, filepath_dst)

    return merged_folder
